name: Ping Website

# Déclenche le workflow à intervalle régulier (toutes les 10 minutes)
on:
  schedule:
    - cron: '*/1 * * * *'
  # Permet également de lancer manuellement le workflow depuis l'interface GitHub
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Pinger le site web
        run: |
          echo "Pinging website..."
          # Remplace l'URL par celle du site que tu souhaites pinger
          curl --max-time 5 -X GET https://analyze-des-sentiments-youtube-1.onrender.com
